apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ziqb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ziqb
    app.kubernetes.io/part-of: tkrw-pr712-0075-0048-app
  name: devfile-sample-ziqb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ziqb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ziqb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-ziqb@sha256:bf86b37cf9deff822824802f6b8888da769dc74b695e3ddbad9fe1c5c476ff32
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
